### ISSUE TITLE
Unablr to upgrade version from 6.9.0 to 9.1.1

### ISSUE THREAD

**Issue by tasyachiru** [maxcellent/javadoc.io#140]
Dear All, 

I would like to ask you, after we upgrade firebase admin to the latest version, its hit this error

Exception in thread "main" java.lang.NoSuchMethodError: com.google.firebase.messaging.Notification.<init>(Ljava/lang/String;Ljava/lang/String;)V
        at com.ebworx.helper.notification.service.FCMService.sendMessageToMultipleDeviceSync(FCMService.java:155)
        at com.ebworx.batch.result.PushNotificationSendProcessResultJob.pushNotificationToDevice(PushNotificationSendProcessResultJob.java:92)
        at com.ebworx.batch.result.PushNotificationSendProcessResultJob.manageResultJob(PushNotificationSendProcessResultJob.java:62)
        at com.ebworx.batch.result.AbstractProcessResultJob.processResultJob(AbstractProcessResultJob.java:36)
        at com.ebworx.batch.controller.AbstractWorkerController.processWork(AbstractWorkerController.java:389)
        at com.ebworx.batch.controller.PushNotificationSendController.main(PushNotificationSendController.java:101)

may i know what method that different from version 6.9.0 to 9.1.1? 

Thank you

**Comment by tasyachiru** [comment]
The error refer to push notification code 

public void sendMessageToMultipleDevicesync PushNotificationRequest request) throws ExecutionException{
List<String> registrationTokens = request. getTokenList ();
Map<String
‚String> customMap = request-getCustomPropertyMap() ;
String notificationId = customMap.get("notificationId");
logger. info"FC push start. Notification Id:"+notificationId);
MulticastMessage message = MulticastMessage. buitder()
setNotification (new Notification(request. getTitle(), request. getMessage() ))
putAllData(request. getCustomPropertyMap () )
.addAllTokens(registrationTokens)
.build() ;
try {
BatchResponse batchResponse = FirebaseMessaging. getInstance). sendMulticastAsync(message). get ();
if (batchResponse. getFailureCount() > 0)
List ‹SendResponse› responses = batchResponse. getResponses() ;
List<String> failedTokens = new ArrayList<>();
for (int i = 0; i < responses.size(); iH) {
if (responses.get (i).isSuccessful ()) {
// The order of responses corresponds to the order of the registration tokens.
failedTokens.add(registrationTokens.get (i));
logger. info "List of tokens that caused failures: " + failedTokens);
logger. info"FC push done. [total of device token = " + registrationTokens.size() + "][success = " + (batchResponse. getSuccessCount ()) + "]");
}catch(InterruptedException e)
logger. error("Sending a push notification ["+notificationId+"] was interrupted", e);

**Comment by maxcellent** [comment]
This is probably the wrong issue tracker. 

We are only hosting javadoc. Please raise issue with libraries' own issue tracker.
